### ISSUE TITLE
父组件修改子组件的style样式不生效

### ISSUE THREAD

**Issue by Konjak2e8** [2023-Online-Hospital-Workshop/Online-Hospital-Management-System#4]
【问题描述】
以本项目中源于element-ui的el-autocomplete组件（见于SearchBox.vue的搜索框）为例，父组件修改子组件属性通常的办法是通过父组件动态绑定修改props中的参数，再将子组件的参数改为这个props中的数值名称。
然而，本问题中需要修改style属性，这个属性是类似script的字符串形式，形如
style="width: 200px;"
【解决尝试】
1. 在子组件中添加width属性，然后在其<style>中绑定input_style：
```
props: {
  width: {
    type: String,
    default: "200px;"
  }
}
...
<style scoped>
.inline-input {
  width: input_width;
}
</style>
```
结果：没有作用，查看网页中搜索框仍为默认的"width: 100%"。

**Comment by davidweidawang** [comment]
这个问题的主要原因在于您在尝试在`<style>`标签中使用Vue变量`input_width`。实际上，Vue中的`<style>`标签并不支持使用动态数据（或者说，Vue模板变量）。它只是一个静态的CSS，Vue无法在此标签中解析它的数据。

你需要做的是在组件的HTML部分使用内联样式（inline style）来实现这种需求。这是一个简单的例子：

```vue
<template>
  <el-autocomplete
    class="inline-input"
    :style="{ width: inputWidth }">
  </el-autocomplete>
</template>

<script>
export default {
  props: {
    inputWidth: {
      type: String,
      default: "200px"
    }
  }
}
</script>
```

这段代码使用了Vue中的动态样式绑定：`:style="{ width: inputWidth }"`。这个绑定意味着，`inputWidth`的值会被用来动态地设置`el-autocomplete`元素的CSS宽度。

注意，Vue会自动把驼峰式命名（camelCase）的变量名转换成短横线分隔（kebab-case）的CSS属性名。因此，`inputWidth`会被转换成`input-width`。

注意：由于JavaScript中的对象键名是固定的，所以在`:style="{ width: inputWidth }"`中，`width`并不会被转换成其他的形式。在这种情况下，你必须要确保你的CSS属性名（比如`width`）是有效的。
